
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.UIManager;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nick
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
 
    boolean encrypted = false;
    GroovyEditGUI parent;
    
    private FileHandler fileHandle;
    private ArrayList<String> settingsList;
    
    private String darkMode;

    public Settings() {
        initComponents();

        fileHandle = new FileHandler("settings.txt", ".txt");
        settingsList = fileHandle.getContentsArry();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDark = new javax.swing.JLabel();
        lblDefaultTxtColor = new javax.swing.JLabel();
        lblMusic = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnPlayPause = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblCurrentTrack = new javax.swing.JLabel();
        tglDark = new javax.swing.JToggleButton();
        btnSelectColor = new javax.swing.JButton();
        lblTextTest = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fileInputTextField = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");

        lblDark.setText("Dark Mode");

        lblDefaultTxtColor.setText("Default Text Color");
        lblDefaultTxtColor.setToolTipText("");

        lblMusic.setText("Music:");
        lblMusic.setAutoscrolls(true);

        btnBack.setText("⏮");
        btnBack.setToolTipText("Restart");
        btnBack.setOpaque(false);

        btnPlayPause.setText("▶⏸");
        btnPlayPause.setToolTipText("Play/Pause");
        btnPlayPause.setOpaque(false);
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });

        btnNext.setText("⏭");
        btnNext.setToolTipText("Next");
        btnNext.setOpaque(false);

        lblCurrentTrack.setText("Nothing Playing");

        tglDark.setText("Enable");
        tglDark.setToolTipText("Enable Dark Mode");
        tglDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglDarkActionPerformed(evt);
            }
        });

        btnSelectColor.setText("Choose");
        btnSelectColor.setToolTipText("Choose Text Color");
        btnSelectColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectColorActionPerformed(evt);
            }
        });

        lblTextTest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextTest.setText("abc ABC");
        lblTextTest.setToolTipText("Sample text");

        jLabel1.setText("FilePath");

        fileInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileInputTextFieldActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        btnPause.setText("⏸");
        btnPause.setToolTipText("Play/Pause");
        btnPause.setOpaque(false);
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Enable");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Encrypt Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDark)
                    .addComponent(lblDefaultTxtColor))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglDark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelectColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTextTest)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDark)
                    .addComponent(tglDark))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDefaultTxtColor)
                    .addComponent(btnSelectColor)
                    .addComponent(lblTextTest, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))//<<<<<<< Music
                .addGap(18, 18, 18)//=======
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMusic)
                    .addComponent(lblCurrentTrack)
                    .addComponent(jLabel1)
                    .addComponent(fileInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnPlayPause)
                    .addComponent(btnNext))
                .addGap(18, 18, 18)
                .addComponent(btnPause)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );//>>>>>>> master

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglDarkActionPerformed
        // When the dark mode toggle is toggled
        
        changeDarkMode(evt.getActionCommand()); // sends "Enable" or "Disable"
        settingsList.set(0, evt.getActionCommand());
        fileHandle.writeTxtFile(fileHandle.arraylistToString(settingsList));

    }//GEN-LAST:event_tglDarkActionPerformed

    private void btnSelectColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectColorActionPerformed
        // Shows user color chooser. Takes rgb value from chosen color and saves it to the appropriate spot in the settings file
        
        Color newColor = JColorChooser.showDialog(this, "Select Color", lblTextTest.getForeground());
        lblTextTest.setForeground(newColor);  
        int rgb = newColor.getRGB();
        settingsList.set(1, Integer.toString(rgb));
        fileHandle.writeTxtFile(fileHandle.arraylistToString(settingsList));
    }//GEN-LAST:event_btnSelectColorActionPerformed

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPauseActionPerformed
            player.clip.setMicrosecondPosition(0);
            clipTimePosition = 0;
            player.clip.start();
    }//GEN-LAST:event_btnPlayPauseActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        filePath = fileInputTextField.getText();
        player.clip.stop();
        player.clip.setMicrosecondPosition(0);
        clipTimePosition = 0;
        player.loadMusic(filePath);
        
        
    }//GEN-LAST:event_loadButtonActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        if(isPlaying)
        {
            clipTimePosition = player.clip.getMicrosecondPosition();
            player.clip.stop();
            btnPause.setText("Resume");
        }
        else
        {
            player.clip.setMicrosecondPosition(clipTimePosition);
            player.clip.start();
            btnPause.setText("Pause");
        }
        isPlaying = !isPlaying;
    }//GEN-LAST:event_btnPauseActionPerformed

    private void fileInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileInputTextFieldActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (parent!=null){
            parent.toggleEncrypt();
            if (this.jToggleButton1.getText()=="Enable"){
                this.jToggleButton1.setText("Disable");
            } else {
                this.jToggleButton1.setText("Enable");
            }

        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
   
    private void changeDarkMode(String eOrD) {
        if (eOrD.equals("Disable")) {
            tglDark.setText("Enable");
            tglDark.setToolTipText("Enable Dark Mode");
            this.getContentPane().setBackground(UIManager.getColor ( "Panel.background" ));
            lblDark.setForeground(Color.BLACK);
            lblDefaultTxtColor.setForeground(Color.BLACK);
            lblMusic.setForeground(Color.BLACK);
            lblCurrentTrack.setForeground(Color.BLACK);
        } else if (eOrD.equals("Enable")) {
            tglDark.setText("Disable");
            tglDark.setToolTipText("Disable Dark Mode");
            this.getContentPane().setBackground(Color.GRAY);
            lblDark.setForeground(Color.WHITE);
            lblDefaultTxtColor.setForeground(Color.WHITE);
            lblMusic.setForeground(Color.WHITE);
            lblCurrentTrack.setForeground(Color.WHITE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnSelectColor;
    private javax.swing.JTextField fileInputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblCurrentTrack;
    private javax.swing.JLabel lblDark;
    private javax.swing.JLabel lblDefaultTxtColor;
    private javax.swing.JLabel lblMusic;
    private javax.swing.JLabel lblTextTest;
    private javax.swing.JButton loadButton;
    private javax.swing.JToggleButton tglDark;
    // End of variables declaration//GEN-END:variables


}
